version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: parking-db
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: ceiba
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
