spring:
  application:
    name: ParkingMan  datasource:    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1    driver-class-name: org.h2.Driver    username: ceiba
    password: ceiba  h2:    console:      enabled: true
server:  port: 8081